### ISSUE TITLE
cloudbeaver Is mongo not supported?

### ISSUE THREAD

**Issue by mingmingqiang** [dbeaver/cloudbeaver#1896]
Please, describe your question in details.
![image](https://github.com/dbeaver/cloudbeaver/assets/86708076/6ff360a5-67d7-45a6-a282-79ce5e5c820b)

**Comment by TatyanaSsau** [comment]
@mingmingqiang CloudBeaver[ Enterprise](https://dbeaver.com/cloudbeaver-enterprise/) already supports MongoDB. You will also have extended support with additional functionality specifically for MongoDB, which will not be in Community Edition (CE) Version even if you add a driver manually.

You can try it for free https://cloudbeaver.io/trial/

**Comment by rashapudenko** [comment]
@TatyanaSsau Can you please elaborate on manual installation in details?
I am trying to add Mongo DB driver to cloudbeaver deployment within AKS.
AKS version - 1.26.3
Deployment manifest:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:23.2.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: web-access
              containerPort: 8978
          livenessProbe:
            httpGet:
              path: /
              port: 8978
              scheme: HTTP
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 5
          envFrom:
          - secretRef:
              name: cloudbeaver-secret
          volumeMounts:
            - name: cloudbeaver-product
              mountPath: /opt/cloudbeaver/conf/product.conf
              subPath: product.conf
            - name: cloudbeaver-sources-user
              mountPath: /opt/cloudbeaver/workspace/user-projects/admin.dbeaver/.dbeaver/data-sources.json
              subPath: data-sources.json
            - name: cloudbeaver-sources-global
              mountPath: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
              subPath: data-sources.json
            - name: cloudbeaver-server
              mountPath: /opt/cloudbeaver/conf/cloudbeaver.conf
              subPath: cloudbeaver.conf
            - name: cloudbeaver-initial-data
              mountPath: /opt/cloudbeaver/conf/initial-data.conf
              subPath: initial-data.conf
      volumes:
        - name: cloudbeaver-product
          configMap:
            name: cloudbeaver-product-configmap
        - name: cloudbeaver-sources-user
          configMap:
            name: cloudbeaver-sources-user-configmap
        - name: cloudbeaver-sources-global
          configMap:
            name: cloudbeaver-sources-global-configmap
        - name: cloudbeaver-server
          configMap:
            name: cloudbeaver-server-configmap
        - name: cloudbeaver-initial-data
          configMap:
            name: cloudbeaver-initial-data-configmap
```


Listed configmaps are for prestored DB connections and for some application settings.

It seems that I can't provision this image with pvc to preserve all the configuration, so I'm playing with configmaps instead.

Correct me if I'm wrong: in order to add drivers to cloudbeaver CE deployment into k8s I should fork cloudbeaver repo, add pom.xml for mongodb driver, build an image and then deploy it? Assumption is based on [wiki](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).

Or is there a way to add driver to already deployed cloudbeaver?

Or, ideally, to add it via init container (for consistency against possible pod recreations)?

In fact, any deployment material would help, maybe some existing helm charts that I missed etc.? :)
