### ISSUE TITLE
allow external connections to the db container

### ISSUE THREAD

**Issue by gudeevjury** [dbeaver/cloudbeaver#1984]
i want runt two services:

- postgresql
- cloudbeaver

i want allow external connections to the db container but restrict the access to cloudbeaver to only be accessible via a custom domain using the nginx host machine

the next is my docker-compose.yml file, im able to access to the db service, but not the cloudbeaver container via 127.0.0.1:15433

```
version: "3.8"
services:
  db:
    image: postgres:15
    container_name: local_pgdb
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - pgcloudbeaver-network-external
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.1.3
    container_name: cloudbeaver_container
    restart: always
    ports:
      - "127.0.0.1:15433:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - pgcloudbeaver-network-external

volumes:
  local_pgdata:
  cloudbeaver_data:

networks:
  pgcloudbeaver-network-external:
    driver: bridge
```
if i remove 127.0.0.1 im able to access via mydomain.com:15433 and the subdomain and the nginx proxy (mysubdomain.mydomain.com), but i dont want this, actually i want to restrict access to the public to the cloudbeaver via the port.

any suggestions about what can i do?

thanks in advance
