### ISSUE TITLE
How to configure dockerized cloudbeaver

### ISSUE THREAD

**Issue by AOne-T** [dbeaver/cloudbeaver#2035]
Please, describe your question in details.
I'm running Cloudbeaver using docker-compose
```
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.2.1
    container_name: cloudbeaver
    restart: always
    ports:
      - 8978:8978
    networks:
      - mynet
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
 ```

In docs (https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration) I found that I can change parameter `sqlTextPreviewMaxLength` in cloudbeaver.conf. Should I make a copy of it from a container, attach it as a volume? Or is there another way?
