### ISSUE TITLE
Cloudbeaver create one session on healthcheck

### ISSUE THREAD

**Issue by webysther** [dbeaver/cloudbeaver#2333]
**Describe the bug**
When using healthcheck inside docker compose cloudbeaver create a session file for every request, as i understand annon request cannot create a session at all, but this is just a guess.

**To Reproduce**
1. Create a docker compose.yml

```yml
version: '3.9'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:23
    container_name: app-sql-editor
    networks:
      cloudbeaver:
    expose:
      - 8978
    healthcheck:
      test: [
        "CMD", "wget", "--spider", "-q", 
        "localhost:8978"
      ]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - workspace:/opt/cloudbeaver/workspace
    restart: unless-stopped

volumes:
  workspace:
    name: "workspace"

networks:
  cloudbeaver:
    name: cloudbeaver
```

3. Open logs:

![image](https://github.com/dbeaver/cloudbeaver/assets/750007/f23769d4-657c-4408-b325-b751af748a45)

**Screenshots**
![image](https://github.com/dbeaver/cloudbeaver/assets/750007/e25ec630-5739-4bf7-b13a-5c13bef90df9)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Browser Chrome 120
 - Version 23

**Additional context**
There no performance degradation, to temperary fix i just remove the health check, but this can be a potential risk for a attack of DDOS if the domain is exposed and get lots of multiple access with risk to fill the disk.
