### ISSUE TITLE
Rootless container fails to start after 24.0.1 upgrade

### ISSUE THREAD

**Issue by bennettmsherman** [dbeaver/cloudbeaver#2502]
**Describe the bug**
I use CB in a rootless container per [the instructions here](https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container#run-cloudbeaver-server-with-non-root-user), and have done so for quite some time.

When I upgraded to 24.0.1 today, CB failed to start due to the lack of a writable home directory.

Logs:

```
tclmetrics-cloudbeaver  | Starting Cloudbeaver Server
tclmetrics-cloudbeaver  | WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
tclmetrics-cloudbeaver  | <title>Invalid Configuration Location</title>The configuration area at '/home/tclmetrics/.local/share/DBeaverData/install-data' could not be created.  Please choose a writable location using the '-configuration' command line option
```

In my case, the user is `tclmetrics`.

**To Reproduce**
Start CB 24.0.1 using rootless configuration described below.

**Screenshots**
N/A

**Desktop (please complete the following information):**

N/A

**Additional context**
Add any other context about the problem here, e.g. error log.

Here's my full docker-compose section for CB:

```
  tclmetrics-cloudbeaver:
    image: "cloudbeaver-with-nuc-gid-and-uid:latest"
    container_name: tclmetrics-cloudbeaver
    restart: "unless-stopped"
    build:
      # Don't run as root
      # Ref: https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container#run-cloudbeaver-server-with-non-root-user
      dockerfile_inline: |
        FROM dbeaver/cloudbeaver:latest
        RUN groupadd --system --gid 972 tclmetrics
        RUN useradd --system --shell /sbin/nologin --uid 973 --gid 972 tclmetrics
        RUN chown --recursive tclmetrics ./
        USER tclmetrics:tclmetrics
    volumes:
      - /var/lib/tclmetrics/cloudbeaver:/opt/cloudbeaver/workspace
      # Inject a custom logging config to disable debug logs
      - /var/lib/tclmetrics/cloudbeaver/logbackOverride.xml:/opt/cloudbeaver/conf/logback.xml:ro
    ports:
      - "127.0.0.1:3003:8978/tcp"
    depends_on:
      - tclmetrics-db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

After creating a home directory and making it writable, CB starts up successfully.

```
diff --git a/tclmetrics/docker-compose.yml b/tclmetrics/docker-compose.yml
index 3cd87bf..258a9a7 100644
--- a/tclmetrics/docker-compose.yml
+++ b/tclmetrics/docker-compose.yml
@@ -23,8 +23,9 @@ services:
       dockerfile_inline: |
         FROM dbeaver/cloudbeaver:latest
         RUN groupadd --system --gid 972 tclmetrics
-        RUN useradd --system --shell /sbin/nologin --uid 973 --gid 972 tclmetrics
-        RUN chown --recursive tclmetrics ./
+        RUN useradd --system --create-home --shell /sbin/nologin --uid 973 --gid 972 tclmetrics
+        RUN chown --recursive tclmetrics:tclmetrics ./
+        RUN chown --recursive tclmetrics:tclmetrics /home/tclmetrics
         USER tclmetrics:tclmetrics
     volumes:
       - /var/lib/tclmetrics/cloudbeaver:/opt/cloudbeaver/workspace
```
