### ISSUE TITLE
Exposing cloudbeaver via Apache proxy

### ISSUE THREAD

**Issue by avhz** [dbeaver/cloudbeaver#3437]
Hi :) 

Having issues with exposing CloudBeaver via Apache. 

I have:

```
RedirectMatch permanent ^/dbeaver$ /dbeaver/

RewriteRule      /dbeaver/(.*) ws://localhost:1234/$1  [P,L]
RewriteRule      /dbeaver/(.*) http://localhost:1234/$1 [P,L]

ProxyPass        /dbeaver/     http://localhost:1234/
ProxyPassReverse /dbeaver/     http://localhost:1234/
```

Port `1234` is forwarded to the cloudbeaver port `8978` in the docker container. 

I also set:

```
CB_SERVER_URL: https://example.com/dbeaver/
CLOUDBEAVER_ROOT_URI: /dbeaver/
```

But I get a 404 Not Found error. 

Anything I've messed up ?

**Comment by EvgeniaBzzz** [comment]
Hi @avhz 
Could you please provide us with server log?
And what CB version do you use?

**Comment by avhz** [comment]
Hi @EvgeniaBzzz :) 

I'm very sorry, it's a bit annoying but I don't have access to the server logs, it's managed elsewhere. I can just see the config. 

My compose is:

```yaml
services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest ## v25 currently I believe
    container_name: dbeaver
    restart: unless-stopped
    ports:
      - 1234:8978
    volumes:
      - ./dbeaver/logs:/opt/cloudbeaver/logs
      - ./dbeaver/workspace:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_URL: https://example.com/dbeaver/
      CLOUDBEAVER_ROOT_URI: /dbeaver/
```
