### ISSUE TITLE
Non-root container

### ISSUE THREAD

**Issue by gdkx6432** [dbeaver/cloudbeaver#349]
Hello,
I would like to run this container in enterprise plateforme  kubernetes but the security office don’t let me because this container is running in root user.

So I would like to ask you to configure this container to run in non-root user. Thanks very much.
I have already try this action but there’s another command needing root action so I don’t want to bug it

Best regards,
Niaina Rand

**Comment by kseniiaguzeeva** [comment]
With regards to your question about our container, it does not require a root user. In addition, if you meant the CloudBeaver documentation, it is written for a standalone docker, not for the kubernetes. 

If you have experienced any problems when you tried to run CloudBeaver, could you please provide me with more details? I will then be able to assess the situation and be able to better help you.

**Comment by MartijnVanAndel** [comment]
I have the same issue: running CloudBeaver on enterprise kubernetes has the following error message: 
_Error: container has runAsNonRoot and image will run as root_

What are UID and PID used to run the container?
Or where can I find the Dockerfile to build the container?

**Comment by MartijnVanAndel** [comment]
I got Cloudbeaver running in enterprise kubernetes, only without persistant storage. 
The yaml to run it, looks like this: 
```
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  ports:
    - name: cbeaver-http
      protocol: TCP
      port: 8978
      targetPort: 8978  
  selector:
    app: cloudbeaver

---
apiVersion: v1
kind: Pod
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  containers:
  - name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
    - containerPort: 8978 
      name: cbeaver-http
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
```

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer and thank you for the report. We will investigate it to assess the issue.

**Comment by pha91** [comment]
@MartijnVanAndel 
Have you tried to add a new user and run the container as this one?
Just have a look at our fix ;) 

```docker
FROM dbeaver/cloudbeaver:21.1.2
RUN addgroup --gid 6000 --system cloudbeaver && adduser --disabled-password --uid 6000 --gid 6000 --gecos '' cloudbeaver
USER 6000
````
after that, we've configured the security context to run as this user:
```
podSecurityContext 
  fsGroup: 6000
  runAsUser: 6000
  runAsGroup: 6000
```

**Comment by MartijnVanAndel** [comment]
> @MartijnVanAndel
> Have you tried to add a new user and run the container as this one?
> Just have a look at our fix ;)

Hi @pha91, 

The fix is working out. I got cloudbeaver running with persistant storage as a statefulset. 
I had to make small adjustments in the image to fix [CVE-2021-33910](https://avd.aquasec.com/nvd/cve-2021-33910). 

```
FROM dbeaver/cloudbeaver:21.1.2
RUN addgroup --gid 6000 --system cloudbeaver && adduser --disabled-password --uid 6000 --gid 6000 --gecos '' cloudbeaver
RUN apt-get update && apt-get install -yq --no-install-recommends \
  libsystemd0 \
  libudev1
USER 6000
```
after this I could successfully run cloudbeaver as statefulset on port 8080:
```
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  ports:
    - name: cbeaver-http
      protocol: TCP
      port: 8080
      targetPort: 8978  
  selector:
    app: cloudbeaver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  selector:
    matchLabels:
      app: cloudbeaver
  serviceName: cloudbeaver
  volumeClaimTemplates:
    - metadata:
        name: cloudbeaver-data
        labels:
          app: cloudbeaver
      spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
      - name: cloudbeaver
        image: _{built_image_from_container_repository}_:latest
        ports:
        - containerPort: 8978
          name: cbeaver-http
        volumeMounts:
        - name: cloudbeaver-data
          mountPath: /opt/cloudbeaver/workspace
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
        securityContext:        
          runAsUser: 6000
          runAsGroup: 6000
```
