### ISSUE TITLE
How to run on k8s

### ISSUE THREAD

**Issue by ysomawar** [dbeaver/cloudbeaver#544]
Please, describe your question in details.
I am trying to run on k8s environment, but UI is not loading. I am getting just dbeaver logo  on top left corner of browser. No error on pod.

following is a yml file user for deployment,

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: dbeaver/cloudbeaver:latest
        ports:
        - containerPort: 8978
          name: cbeaver-http
        env:
        - name: CB_ADMIN_USER
          value: admin
        - name: CB_ADMIN_PASSWORD
          value: admin
        - name: CB_SERVER_NAME
          value: test
        #- name: CB_SERVER_URL
        #  value: https://db.dlgsbox05.serverlessplatform.co.uk/
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: db-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: v451.dlgsbox05.serverlessplatform.co.uk
    http:
      paths:
      - backend:
          service:
            name: db-service
            port:
              number: 8080
        path: /db1
        pathType: ImplementationSpecific
  - host: '*.db.dlgsbox05.serverlessplatform.co.uk'
    http:
      paths:
      - backend:
          service:
            name: db-service
            port:
              number: 8080
        path: /db1
        pathType: ImplementationSpecific

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 8080
      name: cbeaver-http
      targetPort: 8978

```

Could somebody assist me on this.

**Comment by yoavo-datricks** [comment]
You are serving CB under /db1 so I think you must add CB_SERVER_URL with /db1 at the end of it.
That's why it's there.

**Comment by ysomawar** [comment]
Hello @yoavo-datricks , currently I had commented the "CB_SERVER_URL" variable, but I tried by adding /db1 at the end of CB_SERVER_URL, but still same issue. UI is not loading.
Please assist me on this.

**Comment by kseniiaguzeeva** [comment]
Could you please send a screenshot and web console details? It will help me to assess the issue and find a solution.

**Comment by yoavo-datricks** [comment]
You shouldn't do "nginx.ingress.kubernetes.io/rewrite-target: /" and have the CB_SERVER_URL with the /db1.
You shouldn't do any rewrite-target at all, Just have the ingress path and variable identical and it works.

**Comment by ysomawar** [comment]
Hello @yoavo-datricks , 

I tried by removing rewrite-target and CB_SERVER_URL with the /db1, but not working. I am getting 404,

![image](https://user-images.githubusercontent.com/88495035/143267231-e5487e03-7651-4769-88e3-9fd853b6d288.png)

My Updated yaml,
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: dbeaver/cloudbeaver:latest
        ports:
        - containerPort: 8978
          name: cbeaver-http
        env:
        - name: CB_ADMIN_USER
          value: admin
        - name: CB_ADMIN_PASSWORD
          value: admin
        - name: CB_SERVER_NAME
          value: test
        - name: CB_SERVER_URL
          value: https://v451.dlgsbox05.serverlessplatform.co.uk/db1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: db-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: v451.dlgsbox05.serverlessplatform.co.uk
    http:
      paths:
      - backend:
          service:
            name: db-service
            port:
              number: 8080
        path: /db1
        pathType: ImplementationSpecific
  - host: '*.db.dlgsbox05.serverlessplatform.co.uk'
    http:
      paths:
      - backend:
          service:
            name: db-service
            port:
              number: 8080
        path: /db1
        pathType: ImplementationSpecific

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 8080
      name: cbeaver-http
      targetPort: 8978
```
